name: testersite12
favicon: null
layout_spectrum: 0.7423733961768448
typography_spectrum: 0.14495007111690938
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5308085028082132
  lightness: 0.4990186591167003
  saturation: 0.26350354542955756
  rhythmicContrast: 0.839804680319503
purpose: []
